name: Prepare release

on:
  push:
    branches:
      #TODO change to main
      - topic/**

jobs:
  upload_artifacts:
    name: build-test-deployrecipe-uploadartifacts
    uses: ./.github/workflows/reusable-main_build.yml
    with:
      # Disable macos while spdlog crashes its compiler
      # see: https://github.com/conan-io/conan-center-index/issues/8480
      os: >-
        ["ubuntu-latest", "windows-latest"]
      deployrecipe_userchannel: adnn/develop
      step_artifacts: true
    secrets:
      SHREDROBOT_GITHUB_TOKEN: ${{ secrets.SHREDROBOT_GITHUB_TOKEN }}
      ACTION_CACHENAME: ${{ secrets.ACTION_CACHENAME }}
      CONAN_USER_NAME: ${{ secrets.CONAN_USER_NAME }}
      CONAN_USER_PASSWORD: ${{ secrets.CONAN_USER_PASSWORD }}

  archive_release:
    name: archive-release
    needs: upload_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout assets
        uses: actions/checkout@v2
        with:
          repository: ShredEagle/grapito_media
          ref: 'main'
          token: ${{ secrets.SHREDROBOT_GITHUB_TOKEN }}

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Windows-build

      - name: Prepare the release archive
        shell: bash
        run: |
          zip -r grapito.zip grapkimbo.exe assets/

      - name: Upload the release archive
        uses: actions/upload-artifact@v2
        with:
          name: grapito-release
          path: grapito.zip
